[package]
name = "battleship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rusty_tools = {git = "https://github.com/pietrovallardigrohe/Rusty-Tools"}
colored = "2.0.4"